[package]
name = "planifie"
version = "0.1.0"
edition = "2018"

[dev-dependencies]
clap_generate = "3.0.0-beta.4"

[dependencies]
chrono = "0.4.19"
clap = "2.33.3"
dirs = "3.0"
regex = "1"
edit = "0.1"
